server:
  port: 8081
spring:
  application:
    name: bookhotel
  datasource:
    url: jdbc:h2:mem:hotel_booking
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  cache:
    type: simple
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  jwt:
    secret: mysecretkey
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  web:
    path-mapping:
      prometheus: /actuator/prometheus
logging:
  level:
    root: INFO
    com.example.bookhotel: DEBUG
  file:
    name: logs/bookhotel.log